### ISSUE TITLE
Armored Elytra Plugin Failed To Load

### ISSUE THREAD

**Issue by TechnicalityMods** [PimvanderLoos/ArmoredElytra#10]
[ArmoredElytra] Enabling ArmoredElytra v2.4.9*
27.09 19:24:49 [Server] INFO [ArmoredElytra] Enabling stats! Thanks, it really helps!
27.09 19:24:49 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.ItemStack
27.09 19:24:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:172)
27.09 19:24:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
27.09 19:24:49 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
27.09 19:24:49 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
27.09 19:24:49 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
27.09 19:24:49 [Server] WARN at ArmoredElytra.jar//nl.pim16aap2.armoredElytra.nbtEditor.NBTEditor.getNMSClass(NBTEditor.java:239)
27.09 19:24:49 [Server] WARN at ArmoredElytra.jar//nl.pim16aap2.armoredElytra.nbtEditor.NBTEditor.constructNMSClasses(NBTEditor.java:96)
27.09 19:24:49 [Server] WARN at ArmoredElytra.jar//nl.pim16aap2.armoredElytra.nbtEditor.NBTEditor.<init>(NBTEditor.java:57)
27.09 19:24:49 [Server] WARN at ArmoredElytra.jar//nl.pim16aap2.armoredElytra.ArmoredElytra.compatibleMCVer(ArmoredElytra.java:233)
27.09 19:24:49 [Server] WARN at ArmoredElytra.jar//nl.pim16aap2.armoredElytra.ArmoredElytra.onEnable(ArmoredElytra.java:94)
27.09 19:24:49 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
27.09 19:24:49 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
27.09 19:24:49 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
27.09 19:24:49 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
27.09 19:24:49 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
27.09 19:24:49 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
27.09 19:24:49 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
27.09 19:24:49 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
27.09 19:24:49 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
27.09 19:24:49 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
27.09 19:24:49 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
27.09 19:24:49 [Server] WARN [ArmoredElytra] Plugin failed to load! Either your version isn't supported or something went horribly wrong! Please contact pim16aap2!

**Comment by PimvanderLoos** [comment]
You are using a version from 2019 that only supported up to 1.14.
Download version 2.4.15 or compile 3.0 from the master branch to get support for 1.19 and all future versions.
